<?php

/**
 * Farm Our-Sci module.
 */

/**
 * Implements hook_farm_api_oauth2_client().
 */
function farm_oursci_farm_api_oauth2_client() {
  $clients = array();

  // Define the Our-Sci Aggregator OAuth2 client.
  $aggregator_redirect_uris = array(
    'https://oursci.farmos.group/register-farm',
    'https://oursci.farmos.group/authorize-farm',
  );
  $clients['oursci_aggregator'] = array(
    'label' => 'Our-Sci Aggregator',
    'client_key' => 'oursci_aggregator',
    'redirect_uri' => implode("\n", $aggregator_redirect_uris),
  );

  return $clients;
}

/**
 * Implements hook_farm_flags().
 */
function farm_oursci_farm_flags() {
  return array(
    'usda_organic' => t('USDA Organic'),
    'non_gmo' => t('Non-GMO'),
  );
}

/**
 * Implements hook_farm_flags_classes_alter().
 */
function farm_oursci_farm_flags_classes_alter($flag, &$classes) {
  switch ($flag) {
    case 'usda_organic':
      $classes[] = 'btn-success';
      break;
    case 'non_gmo':
      $classes[] = 'btn-info';
      break;
  }
}
