<?php

/**
 * Farm Our-Sci module.
 */

/**
 * Implements hook_menu().
 */
function farm_oursci_menu() {
  $items = array();

  // Produce safety dashboard.
  $items['farm/oursci'] = array(
    'title' => 'Our-Sci Dashboard',
    'page callback' => 'farm_oursci_dashboard',
    'access arguments' => array('access farm dashboard'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['farm/oursci/dashboard'] = array(
    'title' => 'Dashboard',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  // Our-sci settings page.
  $items['farm/oursci/settings'] = array(
    'title' => 'Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('farm_oursci_settings_form'),
    'access arguments' => array('access farm dashboard'),
    'type' => MENU_LOCAL_TASK,
  );

  // API endpoint.
  $items['api/oursci'] = array(
    'page callback' => 'farm_oursci_api_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Our-sci dashboard callback.
 */
function farm_oursci_dashboard() {
  $dashboard = variable_get('farm_oursci_dashboard', '');
  if (empty($dashboard)) {
    return '<p>Specify the dashboard you want in the <a href="/farm/oursci/settings">Our-Sci settings</a>.</p>';
  }
  else {
    return '<div class="embed-responsive embed-responsive-16by9 col-6">
      <iframe class="embed-responsive-item" src="https://app.our-sci.net/dashboard/' . $dashboard . '"></iframe>
    </div>';
  }
}

/**
 * Our-sci settings form.
 */
function farm_oursci_settings_form($form, &$form_state) {
  $form['farm_oursci_dashboard'] = array(
    '#type' => 'textfield',
    '#title' => t('Our-Sci Dashboard'),
    '#default_value' => variable_get('farm_oursci_dashboard', ''),
  );
  return system_settings_form($form);
}

/**
 * Our-sci API callback.
 */
function farm_oursci_api_callback() {

  // If this is a POST request, process the data.
  if ($_SERVER['REQUEST_METHOD'] == 'POST') {

    // Pull the data from the request.
    $data = drupal_json_decode(file_get_contents("php://input"));

    // If data was posted, process it.
    if (!empty($data)) {
      farm_oursci_process_data($data);
    }
  }

  // Return 200 code, always.
  return MENU_FOUND;
}

/**
 * Process data.
 */
function farm_oursci_process_data($data) {

  // Set the timestamp.
  $timestamp = REQUEST_TIME;
  if (!empty($data['timestamp'])) {
    $timestamp = $data['timestamp'];
  }

  // We will create an observation log.
  $type = 'farm_observation';

  // Give it a name.
  $name = 'Our Sci Observation';
  if (!empty($data['title'])) {
    $name = $data['title'];
  }

  // Mark the log as done.
  $done = TRUE;

  // Don't reference any assets.
  $assets = array();

  // Assemble quantity measurements.
  $measurements = array();
  if (!empty($data['quantities'])) {
    foreach ($data['quantities'] as $qty) {
      $measurements[] = $qty;
    }
  }

  // Create a quantity log.
  $log = farm_quantity_log_create($type, $name, $timestamp, $done, $assets, $measurements);

  // Create an entity metadata wrapper for the log.
  $log_wrapper = entity_metadata_wrapper('log', $log);

  // If latitude and longitude are provided, add them to the geofield.
  if (!empty($data['location']['lat']) && !empty($data['location']['lon'])) {
    $lon = $data['location']['lon'];
    $lat = $data['location']['lat'];
    $wkt = 'POINT(' . $lon . ' ' . $lat . ')';
    $log_wrapper->field_farm_geofield[] = array(
      'geom' => $wkt,
    );
  }

  // Save the log (again).
  $log_wrapper->save();
}
